
jobs:

- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: curl -sSL https://install.python-poetry.org | python3
    displayName: Install Poetry

  - script: |
      poetry install
    displayName: 'Install dependencies'

  - script: 
     poetry run python3 -m black --check -l 100 appcenter tests
    displayName: 'Run Black'

  - script: |
      poetry run python3 -m pylint --rcfile=pylintrc appcenter tests
    displayName: 'Lint'

  - script: |
      poetry run python3 -m mypy --ignore-missing-imports appcenter/ tests/
    displayName: 'Type Check'

  - script: |
      poetry run python3 -m pytest tests --cov=appcenter --cov-report html --cov-report xml --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - script: |
      poetry run python3 inlinecss.py htmlcov
    displayName: 'Inline CSS'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  # Publish Code Coverage Results
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/htmlcov
