
jobs:

- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: curl -sSL https://install.python-poetry.org | python3
    displayName: Install Poetry

  - script: |
      poetry install
    displayName: 'Install dependencies'

  - script: 
     poetry run black --check appcenter tests
    displayName: 'Run Black'

  - script: |
      poetry run pylint --rcfile=pylintrc appcenter tests
    displayName: 'Lint'

  - script: |
      poetry run mypy --ignore-missing-imports appcenter/ tests/
    displayName: 'Type Check'
